applications:
  - name: django-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/mazurkevych30/microservice-project.git
      path: charts/django-app
      targetRevision: lesson-4
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app
    url: https://github.com/mazurkevych30/microservice-project.git

repoConfig:
  insecure: "true"
  enableLfs: "true"
